# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "amdgpu" "kvm_amd" "btusb" "mt7291e" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "amdgpu.sg_display=0" "amd_iommu=on" ];

  boot.extraModprobeConfig = ''
    options btusb enable_autosuspend=0
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9ccf2a0d-2828-416e-b2ef-e8907942c136";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-8d2fc873-0f12-4eb8-b004-8fb2d25b3bd6".device = "/dev/disk/by-uuid/8d2fc873-0f12-4eb8-b004-8fb2d25b3bd6";

  # boot.initrd.systemd = {
  #   additionalUpstreamUnits = [ "systemd-tpm2-setup-early.service" ];
  #   storePaths = [
  #     "${config.boot.initrd.systemd.package}/lib/systemd/systemd-tpm2-setup"
  #     "${config.boot.initrd.systemd.package}/lib/systemd/system-generators/systemd-tpm2-generator"
  #   ];
  # };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3453-FA1E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp115s0u1u4c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  hardware.firmware = [ pkgs.linux-firmware ];
}
